"""edit tmp invoices

Revision ID: 99f92e9c2d02
Revises: 7b29acd0ed95
Create Date: 2025-08-01 13:03:09.829865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99f92e9c2d02'
down_revision: Union[str, Sequence[str], None] = '7b29acd0ed95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tmp_invoices', 'number_of_configs',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tmp_invoices', 'number_of_configs',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
