"""edit users table

Revision ID: df38447f9b4b
Revises: 8be73248ace3
Create Date: 2025-07-15 13:05:09.673951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df38447f9b4b'
down_revision: Union[str, Sequence[str], None] = '8be73248ace3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(length=11), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
