"""edit configs table

Revision ID: 1bb6481fa9f0
Revises: df38447f9b4b
Create Date: 2025-07-17 16:34:07.161222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bb6481fa9f0'
down_revision: Union[str, Sequence[str], None] = 'df38447f9b4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vpn_configs', sa.Column('expired', sa.String(length=10), nullable=True))
    op.add_column('vpn_configs', sa.Column('device', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vpn_configs', 'device')
    op.drop_column('vpn_configs', 'expired')
    # ### end Alembic commands ###
