"""add tmpinvoices table

Revision ID: 74fce7022507
Revises: 1bb6481fa9f0
Create Date: 2025-07-21 16:41:12.291656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74fce7022507'
down_revision: Union[str, Sequence[str], None] = '1bb6481fa9f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tmp_invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Integer(), nullable=False),
    sa.Column('days_to_increase', sa.Integer(), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('paid_at', sa.String(length=12), nullable=True),
    sa.Column('created_at', sa.String(length=12), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['vpn_configs.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tmp_invoices')
    # ### end Alembic commands ###
